disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - cyclomatic_complexity
  - nesting
  - switch_case_alignment
  - vertical_parameter_alignment
  - multiple_closures_with_trailing_closure
  - legacy_constructor
  - implicit_getter
  - type_name
opt_in_rules: # some rules are only opt-in
  # Find all the available rules by running:
  # swiftlint rules


excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 170
cyclomatic_complexity: 25

# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
  
  # they can set both implicitly with an array
function_body_length:
  - 51 # warning
  - 61 # error
  
    # they can set both implicitly with an array
function_parameter_count:
  - 7 # warning
  - 8 # error
  
# or they can set both explicitly
file_length:
  warning: 1300
  error: 1500

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    - overview_polyline
    - place_id
    - _delegate
    - _view
    - DEFAULT_LENGTH
    - expires_in
    - access_token
    - refresh_token
    - x
    - y


